changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
classpath=build/classes/java/main:build/resources/main
logLevel=info
diffTypes=tables, columns, primaryKeys, uniqueConstraints, indexes, foreignKeys, sequences
excludeObjects=view:.*

